#!/bin/sh
#
# @name Alien A300
#
# @type Quadcopter x
#
# @maintainer Ondrej Prochazka <prochon4@fel.cvut.cz>
#

. ${R}etc/init.d/rc.mc_defaults

PX4_SIMULATOR=${PX4_SIMULATOR:=gz}

param set-default SIM_GZ_EN 1

param set-default MAV_TYPE 2

param set-default BAT1_N_CELLS 6
param set-default BAT1_CAPACITY 8000
param set-default BAT1_V_EMPTY 3.6
param set-default BAT1_V_CHARGED 4.2
param set-default BAT1_V_LOAD_DROP 0.4

param set-default CA_AIRFRAME 0
param set-default CA_ROTOR_COUNT 4

# Motor geometry in PX4's FRD frame, converted from the FLU poses in
# a300_resources/sdf/a300.sdf.jinja: PX = x, PY = -y, PZ = -z.
#   prop_0 (ccw): sdf x=+0.095 y=-0.117 z=-0.0275
#   prop_1 (ccw): sdf x=-0.095 y=+0.117 z=-0.0275
#   prop_2 (cw):  sdf x=+0.095 y=+0.117 z=-0.0275
#   prop_3 (cw):  sdf x=-0.095 y=-0.117 z=-0.0275
# CT/KM reuse 4001_x500's magnitudes -- these are control-allocator scaling
# terms, not the SDF's physics moment_constant (0.012). Untuned.
param set-default CA_ROTOR0_PX 0.095
param set-default CA_ROTOR0_PY 0.117
param set-default CA_ROTOR0_PZ 0.0275
param set-default CA_ROTOR0_CT 1.0
param set-default CA_ROTOR0_KM 0.06

param set-default CA_ROTOR1_PX -0.095
param set-default CA_ROTOR1_PY -0.117
param set-default CA_ROTOR1_PZ 0.0275
param set-default CA_ROTOR1_CT 1.0
param set-default CA_ROTOR1_KM 0.06

param set-default CA_ROTOR2_PX 0.095
param set-default CA_ROTOR2_PY -0.117
param set-default CA_ROTOR2_PZ 0.0275
param set-default CA_ROTOR2_CT 1.0
param set-default CA_ROTOR2_KM -0.06

param set-default CA_ROTOR3_PX -0.095
param set-default CA_ROTOR3_PY 0.117
param set-default CA_ROTOR3_PZ 0.0275
param set-default CA_ROTOR3_CT 1.0
param set-default CA_ROTOR3_KM -0.06

param set-default SIM_GZ_EC_FUNC1 101
param set-default SIM_GZ_EC_FUNC2 102
param set-default SIM_GZ_EC_FUNC3 103
param set-default SIM_GZ_EC_FUNC4 104

param set-default SIM_GZ_EC_MIN1 0
param set-default SIM_GZ_EC_MIN2 0
param set-default SIM_GZ_EC_MIN3 0
param set-default SIM_GZ_EC_MIN4 0

param set-default SIM_GZ_EC_MAX1 1000
param set-default SIM_GZ_EC_MAX2 1000
param set-default SIM_GZ_EC_MAX3 1000
param set-default SIM_GZ_EC_MAX4 1000
