mrs_uav_controllers:

  velocity_controller:

    track: "/home/adamgb/phd/gazebo_ws/utils/tracks/fig8.yaml"
    policy: "/home/adamgb/phd/data/policies/master_thesis/so3-GOD.pt"

    # policy action scaling
    v_max: [10.0, 10.0, 3.0] # [m/s]
    wz_max: 3.0 # [rad/s]

    # SO(3) velocity controller gains
    k_v: [3.0, 3.0, 4.0]
    k_R: [8.0, 8.0, 1.0]

    collective_thrust_max: 80.0 # [N]

    omega_output_min: [-6.0, -6.0, -3.0] # [rad/s]
    omega_output_max: [6.0, 6.0, 3.0] # [rad/s]
    throttle_clamp_min: 0.0
    throttle_clamp_max: 0.9
